"""empty message

Revision ID: 1a6d34401c45
Revises: b4635be44469
Create Date: 2017-03-26 09:19:15.220349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6d34401c45'
down_revision = 'b4635be44469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimes', sa.Column('offense_end_date', sa.DateTime(), nullable=True))
    op.add_column('crimes', sa.Column('offense_start_date', sa.DateTime(), nullable=True))
    op.add_column('crimes', sa.Column('report_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crimes', 'report_date')
    op.drop_column('crimes', 'offense_start_date')
    op.drop_column('crimes', 'offense_end_date')
    # ### end Alembic commands ###
