"""empty message

Revision ID: 44199518c4d4
Revises: ea35bf351995
Create Date: 2017-03-25 21:02:00.198772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44199518c4d4'
down_revision = 'ea35bf351995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crimes_latitude'), 'crimes', ['latitude'], unique=False)
    op.create_index(op.f('ix_crimes_longitude'), 'crimes', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crimes_longitude'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_latitude'), table_name='crimes')
    # ### end Alembic commands ###
