"""empty message

Revision ID: 6a2ce3d46e8b
Revises: 44199518c4d4
Create Date: 2017-03-25 21:02:58.064297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a2ce3d46e8b'
down_revision = '44199518c4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crimes_latitude', table_name='crimes')
    op.drop_index('ix_crimes_longitude', table_name='crimes')
    op.drop_column('crimes', 'latitude')
    op.drop_column('crimes', 'longitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimes', sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('crimes', sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_crimes_longitude', 'crimes', ['longitude'], unique=False)
    op.create_index('ix_crimes_latitude', 'crimes', ['latitude'], unique=False)
    # ### end Alembic commands ###
