"""empty message

Revision ID: 6ef5eaccb54d
Revises: 6a2ce3d46e8b
Create Date: 2017-03-25 21:03:23.179968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef5eaccb54d'
down_revision = '6a2ce3d46e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimes', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('crimes', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index(op.f('ix_crimes_latitude'), 'crimes', ['latitude'], unique=False)
    op.create_index(op.f('ix_crimes_longitude'), 'crimes', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crimes_longitude'), table_name='crimes')
    op.drop_index(op.f('ix_crimes_latitude'), table_name='crimes')
    op.drop_column('crimes', 'longitude')
    op.drop_column('crimes', 'latitude')
    # ### end Alembic commands ###
