"""empty message

Revision ID: 9459ed23ab04
Revises: 
Create Date: 2017-03-25 14:50:01.525396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9459ed23ab04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
