"""empty message

Revision ID: b4635be44469
Revises: 6ef5eaccb54d
Create Date: 2017-03-26 09:18:52.866058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4635be44469'
down_revision = '6ef5eaccb54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crimes', 'report_date')
    op.drop_column('crimes', 'offense_start_date')
    op.drop_column('crimes', 'offense_end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimes', sa.Column('offense_end_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('crimes', sa.Column('offense_start_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('crimes', sa.Column('report_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
