"""empty message

Revision ID: c0489cf9baa6
Revises: 9459ed23ab04
Create Date: 2017-03-25 15:09:14.255079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0489cf9baa6'
down_revision = '9459ed23ab04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offense_type', sa.String(), nullable=True),
    sa.Column('offense_description', sa.String(), nullable=True),
    sa.Column('report_date', sa.String(), nullable=True),
    sa.Column('offense_start_date', sa.String(), nullable=True),
    sa.Column('offense_end_date', sa.String(), nullable=True),
    sa.Column('block', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('beat', sa.String(), nullable=True),
    sa.Column('census_tract', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'test_pkey')
    )
    op.drop_table('crimes')
    # ### end Alembic commands ###
