"""empty message

Revision ID: f3b05877c7a4
Revises: c0489cf9baa6
Create Date: 2017-03-25 19:42:12.048855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b05877c7a4'
down_revision = 'c0489cf9baa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimes', sa.Column('time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crimes', 'time')
    # ### end Alembic commands ###
